class MyRunnableTread implements Runnable{
    public void run(){
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
        System.out.println("i am runnaing thread");
    }

}
class MyRunnableTread2 implements Runnable{
    public void run(){
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
        System.out.println("i am also runnaing thread 2");
    }

}

public class runnable_interface {
    public static void main(String[] args) {
        MyRunnableTread R1 = new MyRunnableTread();
         Thread gun1 = new Thread(R1);

        MyRunnableTread2 R2 = new MyRunnableTread2();
        Thread gun2 = new Thread(R2);

        gun1.start();
        gun2.start();

        
    }
}
